### ISSUE TITLE
next step should be...

### ISSUE THREAD

**Issue by RH-sdavey** [Ladia-m/Piskvorky#6]
actual connect 4  ( not 5 )  should look like this ...
![image](https://user-images.githubusercontent.com/32485509/47594920-d3104b80-d97d-11e8-8f36-aad848364da0.png)
that is if the user clicks on a column, then the "next available" bottom cell in that column should be filled, not the actual cell they click on....

**Comment by Ladia-m** [comment]
The game should be piskvorky, not connect 4, I just get confused by English names. Sorry for this confusion.
